/**
 * Proposal section model.
 *
 * A proposal version's `sections` column is a JSON array of these. Versions are
 * immutable, so this shape is effectively an on-disk format — add fields, never
 * repurpose existing ones, or old versions stop rendering.
 */

export interface ProposalSection {
  /** Stable slug. Used to target a single-section regeneration. */
  slug: string;
  title: string;
  /** Safe-subset HTML — see `sanitizeSectionHtml`. */
  html: string;
}

/** The default skeleton a new proposal starts from. */
export const DEFAULT_SECTIONS: readonly { slug: string; title: string }[] = [
  { slug: "executive-summary", title: "Executive Summary" },
  { slug: "understanding", title: "Understanding of Requirements" },
  { slug: "proposed-solution", title: "Proposed Solution" },
  { slug: "architecture", title: "Technical Architecture" },
  { slug: "delivery-approach", title: "Delivery Approach" },
  { slug: "team", title: "Team & Governance" },
  { slug: "timeline", title: "Timeline & Milestones" },
  { slug: "pricing", title: "Commercials" },
  { slug: "assumptions", title: "Assumptions & Risks" },
  { slug: "why-us", title: "Why MoreYeahs" },
];

/**
 * Tags the renderers (HTML preview, react-pdf, docx) all understand. Anything
 * outside this set is stripped rather than escaped — a proposal that silently
 * renders `<script>` as visible text looks broken; dropping it looks clean.
 */
const ALLOWED_TAGS = new Set([
  "p", "br", "strong", "em", "u", "ul", "ol", "li", "h3", "h4", "table", "thead",
  "tbody", "tr", "th", "td", "a", "blockquote", "code", "pre",
]);

/**
 * Strip everything outside the safe subset.
 *
 * This is a whitelist over the tag vocabulary the exporters support — it is NOT
 * a general-purpose XSS sanitiser and must not be relied on as the only defence
 * for rendering untrusted HTML in a browser. Proposal HTML is authored by
 * authenticated org members or generated by Claude, both inside the tenant
 * boundary; the export pipeline is the consumer we're protecting.
 */
export function sanitizeSectionHtml(html: string): string {
  return (
    html
      // Drop script/style wholesale — content included, not just the tags.
      .replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, "")
      // Drop inline event handlers and javascript: URLs.
      .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, "")
      .replace(/(href|src)\s*=\s*("|')\s*javascript:[^"']*\2/gi, "")
      // Strip any tag not on the allow-list, keeping its inner text.
      .replace(/<\/?([a-zA-Z][a-zA-Z0-9-]*)\b[^>]*>/g, (match, tag: string) =>
        ALLOWED_TAGS.has(tag.toLowerCase()) ? match : "",
      )
      .trim()
  );
}

/** Coerce arbitrary JSON from the DB back into typed sections. */
export function parseSections(value: unknown): ProposalSection[] {
  if (!Array.isArray(value)) return [];
  return value.flatMap((item): ProposalSection[] => {
    const row = item as Partial<ProposalSection>;
    if (typeof row?.slug !== "string" || typeof row?.title !== "string") return [];
    return [
      {
        slug: row.slug,
        title: row.title,
        html: typeof row.html === "string" ? row.html : "",
      },
    ];
  });
}

/** Sanitise on the way in, so no version is ever stored with unsafe markup. */
export function normaliseSections(sections: ProposalSection[]): ProposalSection[] {
  return sections.map((s) => ({
    slug: s.slug,
    title: s.title,
    html: sanitizeSectionHtml(s.html),
  }));
}

/** Plain text for a section, for AI context and Word export fallbacks. */
export function sectionToPlainText(section: ProposalSection): string {
  return section.html
    .replace(/<\/(p|li|h3|h4|tr|blockquote)>/gi, "\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}
